name: Build and Release

on: 
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release (for example v1.2.3)'
        required: true
        default: 'v0.0.8'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production --base-href ./

      - name: Set Release Tag
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "RELEASE_TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Package and Publish Electron
        if: env.IS_RELEASE == 'true'
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --publish always

      - name: Build Changelog
        if: env.IS_RELEASE == 'true'
        id: changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare-link: false
          semver: false

      - name: Update GitHub Release
        if: env.IS_RELEASE == 'true'
        uses: ncipollo/release-action@v1.20.0
        with:
          body: ${{ steps.changelog.outputs.changelog }} 
          allowUpdates: true
          tag: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}