name: Build/release

on: 
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'

      - name: Generate icons
        run: node build/generate-icons.js

      # Chạy khi push code bình thường (không phải tag)
      - name: Package Electron
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx electron-builder --publish never

      # Chạy khi push một tag (v1.0.0, v2.1.0,...)
      - name: Package and Publish Electron
        if: startsWith(github.ref, 'refs/tags/')
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx electron-builder --publish always

      - name: Build Changelog
        if: startsWith(github.ref, 'refs/tags/')
        id: changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare-link: false
          semver: false

      - name: Update GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1.20.0
        with:
          body: ${{ steps.changelog.outputs.changelog }} 
          allowUpdates: true
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}